### ISSUE TITLE
AssimpImporter: Should normalize filepaths for external image paths

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum-plugins#101]
I just encountered a FBX which had a filepath with `\` along the lines of:

```
[error] Trade::AbstractImporter::openFile(): cannot open file /a/unix/path/Assets/Something/Textures\[...]_Diffuse.png
```

It turns out that Assimp does not normalize filepaths before opening. A workaround is to [set a file callback](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1AbstractImporter.html#adc2889e9ba4c89df2f0f559c94f44c3c).

Might eventually get around to creating a PR.

**Comment by mosra** [comment]
Fixed with #102. Yay, Assimp!
