### ISSUE TITLE
AssimpImporter: Embedded textures fail to load with FBX

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum-plugins#127]
Unfortunately I cannot provide the file in question here, but some investigation resulted in finding the following comment:
https://github.com/assimp/assimp/issues/1830#issuecomment-372945539

Which seems to indicate that testing `*` prefix for the filename is no longer sufficient to detect embedded images.
Instead we would try to load every image with `scene->GetEmbeddedTexture(texture_file.C_Str())` and if it fails, load it as file.

We might fix this soon, since that is a fairly common case for scene files out in the wild.

**Comment by mosra** [comment]
If you submit a PR, is it possible to craft a minimal FBX file to reproduce this? Similarly how @pezcode made the test file for material layers using some Python library.

**Comment by mosra** [comment]
Fixed with #128.
