### ISSUE TITLE
Proper use of INT16_MAX

### ISSUE THREAD

**Issue by ytain** [mosra/magnum-plugins#14]
Could you please change the use of INT16_MAX in OpenDdl/Type.h to 

```
#include <limits>

#define INT16_MAX std::numeric_limits<std::int16_t>::max()
```

Cause it is more C++11 idiomatic and free of warning across the compilers.

**Comment by mosra** [comment]
Can you post also examples of the warnings, please? This was in non-templated code so I saw no reason in writing so much of code, because it is neither more correct nor less error prone (I can still make a typo and write `uint16_t` instead of `int16_t`, though it might be seen as more C++11 idiomatic.

Also, I fear that `max()` is/was not `constexpr` on some compilers. That would be actual problem.

**Comment by ytain** [comment]
Here are the warnings:

```
Scanning dependencies of target OpenGexImporterObjects
[ 54%] Building CXX object src/MagnumPlugins/OpenGexImporter/CMakeFiles/OpenGexImporterObjects.dir/OpenGexImporter.cpp.o
In file included from /magnum-plugins/src/MagnumPlugins/OpenGexImporter/OpenGexImporter.cpp:44:
In file included from /include/MagnumPlugins/OpenGexImporter/OpenDdl/Document.h:39:
/include/MagnumPlugins/OpenGexImporter/OpenDdl/Type.h:39:9: warning: 'INT16_MAX' macro redefined [-Wmacro-redefined]
#define INT16_MAX std::numeric_limits<std::int16_t>::max()
        ^
/usr/include/stdint.h:69:9: note: previous definition is here
#define INT16_MAX        32767
        ^
1 warning generated.
[ 56%] Building CXX object src/MagnumPlugins/OpenGexImporter/CMakeFiles/OpenGexImporterObjects.dir/OpenDdl/OpenDdl.cpp.o
In file included from /magnum-plugins/src/MagnumPlugins/OpenGexImporter/OpenDdl/OpenDdl.cpp:26:
In file included from /magnum-plugins/src/MagnumPlugins/OpenGexImporter/OpenDdl/Document.h:39:
/include/MagnumPlugins/OpenGexImporter/OpenDdl/Type.h:39:9: warning: 'INT16_MAX' macro redefined [-Wmacro-redefined]
#define INT16_MAX std::numeric_limits<std::int16_t>::max()
        ^
/usr/include/stdint.h:69:9: note: previous definition is here
#define INT16_MAX        32767
        ^
1 warning generated.
[ 57%] Building CXX object src/MagnumPlugins/OpenGexImporter/CMakeFiles/OpenGexImporterObjects.dir/OpenDdl/parsers.cpp.o
In file included from /magnum-plugins/src/MagnumPlugins/OpenGexImporter/OpenDdl/parsers.cpp:33:
/include/MagnumPlugins/OpenGexImporter/OpenDdl/Type.h:39:9: warning: 'INT16_MAX' macro redefined [-Wmacro-redefined]
#define INT16_MAX std::numeric_limits<std::int16_t>::max()
        ^
/usr/include/stdint.h:69:9: note: previous definition is here
#define INT16_MAX        32767
        ^
1 warning generated.
[ 57%] Built target OpenGexImporterObjects
```

**Comment by ytain** [comment]
Also this stackoverflow question with the answer clarifies on how to use the C++11 way:

http://stackoverflow.com/questions/3233054/error-int32-max-was-not-declared-in-this-scope

**Comment by mosra** [comment]
Um. Correct me if I'm wrong, but these warnings come from your proposed change and not from the code that was [originally there](https://github.com/mosra/magnum-plugins/blob/def67c13568a8d0687b9d956366414e3a1592a0f/src/MagnumPlugins/OpenGexImporter/OpenDdl/Document.h#L39). Or do you mean that you have a platform on which `INT16_MAX` is missing?

**Comment by ytain** [comment]
The warnings comes from your unmodified source code. When I add my own substitution as shown in the first post above, no warnings.

**Comment by mosra** [comment]
But from what I see, the warnings are about 

```cpp
#define INT16_MAX std::numeric_limits<std::int16_t>::max()
```

and the code has no such thing in it: https://github.com/mosra/magnum-plugins/blob/def67c13568a8d0687b9d956366414e3a1592a0f/src/MagnumPlugins/OpenGexImporter/OpenDdl/Document.h#L39

**Comment by ytain** [comment]
The warnings must come from the std headers, not your magnum-plugins headers. That's what is is about. There's some wrong use of std headers somewhere else (possibly mixing C targeted headers with C++ headers)

**Comment by mosra** [comment]
No. 

In your post above:

>
```
/include/MagnumPlugins/OpenGexImporter/OpenDdl/Type.h:39:9: warning: 'INT16_MAX' macro redefined [-Wmacro-redefined]
#define INT16_MAX std::numeric_limits<std::int16_t>::max()
        ^
/usr/include/stdint.h:69:9: note: previous definition is here
#define INT16_MAX        32767
```
>

Relevant snippet from [Type.h, current master, def67c13568a8d0687b9d956366414e3a1592a0f, lines 28-43](https://github.com/mosra/magnum-plugins/blob/def67c13568a8d0687b9d956366414e3a1592a0f/src/MagnumPlugins/OpenGexImporter/OpenDdl/Type.h#L39):

```cpp
/** @file
 * @brief Enum @ref Magnum::OpenDdl::Type, @ref Magnum::OpenDdl::PropertyType, constant @ref Magnum::OpenDdl::UnknownIdentifier
 */

#include <Magnum/Magnum.h>

namespace Magnum { namespace OpenDdl {

/**
@brief OpenDDL type
@see @ref Structure::type()
*/
enum class Type: UnsignedInt {
    /** Boolean. Stored in `bool` type. */
    Bool,
```

No such define on line 39. I also did a glob over the whole project and `INT16_MAX` is defined only once and that's its usage, not any `#define`. So I'm sorry, but I have no idea what you are talking about. Is your installation done from a clean working copy?

**Comment by mosra** [comment]
Oh, maybe I know -- the compiler is for some reason using system-installed headers when building the project. That should not be -- can you remove your system-wide installation and try again? The warning should disappear.

**Comment by ytain** [comment]
The system installed headers comes with XCode and the command line tools (xcode-select) only link to them automatically. I've been using XCode for so long and usually start a fresh installation of XCode at every major version release.

**Comment by mosra** [comment]
Um. No, I mean -- there's a file named `/include/MagnumPlugins/OpenGexImporter/OpenDdl/Type.h` somewhere on your system, which means some broken/modified version of magnum-plugins was once installed on your system.

I don't know why and why the compiler prefers it over the includes that are *inside* the project, so please try getting rid of that broken system-wide magnum-plugins installation and try compiling the project again, with a clean Git working copy. The warnings *will* disappear.

**Comment by ytain** [comment]
I don't install in system wide folders. I prefer to install to my own folder in the home folder. I use cmake arguments to force to install to my own folder instead of system-wide install. That way I keep clean the OS.

Also I did a ```git fetch origin && git reset --HARD && git pull``` and no errors

Look at this script I use in the terminal:

```
function compile_with_cmake() {
    cd $1
    if [ -e CMakeLists.txt ]; then
	echo "==========================================================================="
	echo "Compiling $1 with CMake"
	echo "==========================================================================="
	if [ -d build ]; then
	    echo "Emptying the build folder ..."
	    echo "==========================================================================="
	    rm -rf build
	    mkdir build
	else 
	    mkdir build
	fi
	cd build
	local output_folder='~/temporary/final'
	local library_path=$output_folder'/lib'
	local pkgconfigpath=$library_path'/pkgconfig'
	local args_to_be_passed_to_cmake="$2"
	#echo "$output_folder"
	#echo "$library_path"
	#echo "$args_to_be_passed_to_cmake"
	#export CPPFLAGS="$output_folder/include"
	#export CXXFLAGS="$output_folder/include"
	LDFLAGS="-L${output_folder}/lib" cmake .. -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH=$output_folder -DCMAKE_INSTALL_PREFIX=$output_folder $args_to_be_passed_to_cmake
	cmake --build .
	cmake --build . --target install
	echo "==========================================================================="
	cd ..
    fi
    cd ..
}



cd libiconv-1.14
make clean
./configure --prefix=~/temporary/final --with-pic --disable-shared --enable-static 
make install
make clean
cd ..

cd libpng
make clean
LT_SYS_LIBRARY_PATH="~/temporary/final/lib" LDFLAGS="-L~/temporary/final/lib" ./configure --prefix=~/temporary/final --with-pic --disable-shared --enable-static
make install
make clean
cd ..


compile_with_cmake sdl2 "-DSDL_STATIC=ON -DSDL_SHARED=OFF"



cd libjpeg-turbo
make clean
./configure --prefix=~/temporary/final --with-pic --disable-shared --enable-static --host x86_64-apple-darwin
make install
make clean
cd ..

compile_with_cmake freetype2 "-DWITH_HarfBuzz=OFF -DWITH_ZLIB=ON -DWITH_BZip2=ON -DWITH_PNG=ON -DBUILD_SHARED_LIBS=OFF"

cd harfbuzz
make clean
./configure --prefix=~/temporary/final --with-pic --disable-shared --enable-static --host x86_64-apple-darwin --with-glib=no --with-icu=no --with-cairo=no --with-fontconfig=no
make install
make clean
cd ..

compile_with_cmake corrade "-DBUILD_STATIC=ON -DBUILD_STATIC_PIC=ON"
compile_with_cmake magnum "-DBUILD_STATIC=ON -DBUILD_STATIC_PIC=ON -DBUILD_PLUGINS_STATIC=ON -DWITH_MAGNUMINFO=ON -DWITH_FONTCONVERTER=ON -DWITH_DISTANCEFIELDCONVERTER=ON -DWITH_MAGNUMFONT=ON -DWITH_MAGNUMFONTCONVERTER=ON -DWITH_OBJIMPORTER=ON -DWITH_MESHTOOLS=ON -DWITH_PRIMITIVES=ON -DWITH_SHAPES=ON -DWITH_SCENEGRAPH=ON -DWITH_SHADERS=ON -DWITH_TEXT=ON -DWITH_TEXTURETOOLS=ON -DWITH_WINDOWLESSCGLAPPLICATION=ON -DWITH_CGLCONTEXT=ON -DWITH_SDL2APPLICATION=ON -DWITH_TGAIMPORTER=ON -DWITH_TGAIMAGECONVERTER=ON"
compile_with_cmake magnum-plugins "-DBUILD_STATIC=ON -DBUILD_STATIC_PIC=ON -DWITH_ANYIMAGEIMPORTER=ON -DWITH_ANYIMAGECONVERTER=ON -DWITH_ANYSCENEIMPORTER=ON -DWITH_DDSIMPORTER=ON -DWITH_FREETYPEFONT=ON -DWITH_HARFBUZZFONT=OFF -DWITH_JPEGIMPORTER=ON -DWITH_OPENGEXIMPORTER=ON -DWITH_PNGIMPORTER=ON -DWITH_STANFORDIMPORTER=ON -DWITH_STBIMAGEIMPORTER=ON -DWITH_STBPNGIMAGECONVERTER=ON"
```

**Comment by Squareys** [comment]
> don't install in system wide folders. I prefer to install to my own folder in the home folder.

Then remove the magnum-plugins includes from there instead ;)

**Comment by ytain** [comment]
Weird, the warnings are gone after I deleted the headers/libraries for MagnumPlugins from the output folder. It seems that the cmake has a subtle bug in regard to the presence of old headers in the output folder. I'll have to see if that bug is there at cmake.
Sorry for wasting your time.

**Comment by mosra** [comment]
I fear this might be caused by adding the folders to "system" include path, then they are for some reason preferred by GCC over local ones. Not a CMake fault, I think.

Glad to have this resolved ;)

**Comment by ytain** [comment]
Maybe a good idea is to have an uninstall target like outlined there at https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F

**Comment by mosra** [comment]
This would way too much effort to make it really do the right thing and not breaking people systems with broken library dependencies, removing files that were not meant to be removed etc. I would prefer relying on some package manager -- you are on OSX, so why not Homebrew? Currently it's just:

```sh
brew install --HEAD mosra/magnum/magnum-plugins # install latest Git master
brew reinstall magnum-plugins # update to latest Git master
brew uninstall magnum-plugins # get rid of the package, cleanly
```

Of course then it's harder to put your patches in, but you can always do your own derived Homebrew package.

**Comment by ytain** [comment]
The problem with homebrew is that it forces you to install system-wide way and I don't want to clutter the OS with developmental changes that happens several times a day. So that's why I do the manual git way from terminal to my own folder.

**Comment by mosra** [comment]
I understand. The other way we're currently doing at work with Magnum and other project dependencies is: build and install each project to a clean folder and make `*.tar.xz` out of it. The resulting `*.tar.xz` folders are then extracted in to some location, which is consumed by other projects. Upgrading is then done by deleting everything from that location and extracting a fresh set of `*.tar.xz` archives there. That way we always have a clean state, not relying on accidental manual changes or files that appeared out of nowhere. This is a bit annoying to do manually, so we have it scripted and a CI does the job of preparing the archives in a clean environment.

Another option might be to have each project installed in a completely separate location (`~/temporary/final/magnum`, `~/temporary/final/magnum-plugins`, ...) and then specifying all the paths in `CMAKE_PREFIX_PATH`. Then you can replace an installation just by deleting and overwriting a single directory.
