### ISSUE TITLE
Could NOT find Magnum (missing: AnySceneImporter)

### ISSUE THREAD

**Issue by namkazt** [mosra/magnum-plugins#17]
Hi,

I was setup and able to run sdl2 application. but when i try to load plugin. it alway error like that 
"Could NOT find Magnum (missing: AnySceneImporter)" example of load AnySceneImporter

i'm using static lib

```
find_package(Magnum REQUIRED
	MeshTools
    Shaders
    SceneGraph
	AnySceneImporter
    Sdl2Application)

set_directory_properties(PROPERTIES CORRADE_USE_PEDANTIC_FLAGS ON)

add_executable(MyApplication MyApplication.cpp

)

target_link_libraries(MyApplication
    Magnum::Application
    Magnum::Magnum
	Magnum::MeshTools
    Magnum::SceneGraph
    Magnum::Shaders
	Magnum::AnySceneImporter
	)

```

here is Cmake-gui project
![camw](https://cloud.githubusercontent.com/assets/6035916/18376646/1d11018c-768b-11e6-89e9-025fcb5d6fa2.png)

**Comment by namkazt** [comment]
it should be : 
find_package(MagnumPlugins REQUIRED
	AnySceneImporter)

target_link_libraries(MagnumPlugins::AnySceneImporter)

you should fix for document about it.
http://mosra.cz/blog/magnum-doc/plugins.html - Static plugins

**Comment by mosra** [comment]
Hi,

thanks for the detailed report. The thing is that in the particular documentation snippet, the `TgaImporter` was really part of the `Magnum` package and not the `MagnumPlugins` package, so the documentation was in fact correct, but confusing. I changed the documentation to show the more common case in mosra/magnum@782ec2413073982d5bb0aa1e93ae692df8ba8657.
