### ISSUE TITLE
Magnum-Plugins no longer compile statically

### ISSUE THREAD

**Issue by alicemargatroid** [mosra/magnum-plugins#28]
So, I always compile everything statically because MingW and Windows. I have had scripts and CMake files that worked for a long time that did this all for me. However, a while back, I started getting these errors:

> 
> CMake Error at magnum/engine/corrade/modules/UseCorrade.cmake:511 (install):
>   install TARGETS given no ARCHIVE DESTINATION for static library target
>   "AnyAudioImporter".
> Call Stack (most recent call first):
>   magnum/engine/magnum-plugins/src/MagnumPlugins/CMakeLists.txt:31 (corrade_add_static_plugin)
>   magnum/engine/magnum-plugins/src/MagnumPlugins/AnyAudioImporter/CMakeLists.txt:55 (add_plugin)
> 
> 
> CMake Error at magnum/engine/corrade/modules/UseCorrade.cmake:511 (install):
>   install TARGETS given no ARCHIVE DESTINATION for static library target
>   "AnyImageImporter".
> Call Stack (most recent call first):
>   magnum/engine/magnum-plugins/src/MagnumPlugins/CMakeLists.txt:31 (corrade_add_static_plugin)
>   magnum/engine/magnum-plugins/src/MagnumPlugins/AnyImageImporter/CMakeLists.txt:53 (add_plugin)
> 
> 
> CMake Error at magnum/engine/corrade/modules/UseCorrade.cmake:511 (install):
>   install TARGETS given no ARCHIVE DESTINATION for static library target
>   "DrFlacAudioImporter".
> Call Stack (most recent call first):
>   magnum/eng
> st recent call first):
>   magnum/engine/magnum-plugins/src/MagnumPlugins/CMakeLists.txt:31 (corrade_add_static_plugin)
>   magnum/engine/magnum-plugins/src/MagnumPlugins/DrFlacAudioImporter/CMakeLists.txt:58 (add_plugin)
> 
> 
> CMake Error at magnum/engine/corrade/modules/UseCorrade.cmake:511 (install):
>   install TARGETS given no ARCHIVE DESTINATION for static library target
>   "StbImageImporter".
> Call Stack (most recent call first):
>   magnum/engine/magnum-plugins/src/MagnumPlugins/CMakeLists.txt:31 (corrade_add_static_plugin)
>   magnum/engine/magnum-plugins/src/MagnumPlugins/StbImageImporter/CMakeLists.txt:55 (add_plugin)
> 
> 
> -- Found Magnum: /home/ren/Desktop/experimental/ArcAngel/magnum/engine/magnum/src  found components:  TextureTools Text 
> CMake Error at magnum/engine/corrade/modules/UseCorrade.cmake:511 (install):
>   install TARGETS given no ARCHIVE DESTINATION for static library target
>   "StbTrueTypeFont".
> Call Stack (most recent call first):
>   magnum/engine/magnum-plugins/src/MagnumPlugins/CMakeLists.txt:31 (corrade_add_static_plugin)
>   magnum/engine/magnum-plugins/src/MagnumPlugins/StbTrueTypeFont/CMakeLists.txt:57 (add_plugin)
> 
> 

I've tried to investigate this, but I can't figure it out. This is blocking me from doing any further work on Magnum (and my own game, sadly enough). Any advice is helpful, as I'd really like to get back to work now that I have time free!

**Comment by mosra** [comment]
Some time ago I did a change in mosra/corrade@8c5dcb653062a3ac23ff2513448f59a47aa96506 order to have `*.dll`s in `bin/` and `*.lib` in `lib/` on Windows (as it should be), so that may caused this issue. Will investigate and fix today. Sorry about the mess :(

**Comment by mosra** [comment]
@alicemargatroid I'm having problems reproducing this. The error is apparently caused by the `install()` command getting empty `DESTINATION`. Are you on latest `master` in all the subproject repos? It looks to me like you have some stale `FindMagnum.cmake` module somewhere which is missing some variables that I added when making the change mentioned above.

**Comment by alicemargatroid** [comment]
@mosra Looks like CMake installed `FindMagnum.cmake` and `FindMagnumPlugins.cmake` for reasons known only to CMake, which is causing the conflict even with a clean build.

All fixed, no problems with the bumpy ride; it's basically impossible to test without a hundred VMs!

**Comment by mosra** [comment]
Glad to see it's solved :)

I double checked that I'm actually testing the static build on Windows (I am, as part of the Windows RT build on AppVeyor, though not on MinGW), so hopefully next time I break stuff the CI kicks me back :)
