### ISSUE TITLE
Upgrade package/debian libpng dependency version

### ISSUE THREAD

**Issue by leokolln** [mosra/magnum-plugins#38]
The Debian packages depends on `libpng12-dev` / `libpng12-0` that are outdated, insecure and unavailable for Ubuntu after 16.04.

Recommend upgrade to `libpng-dev` and `libpng16-16`.

**Comment by mosra** [comment]
Hey, thank you!

I am just in the middle of doing a pre-release preparations and you just crossed a bunch of things off my TODO list :) I'll integrate your suggestions as soon as possible.

**Comment by mosra** [comment]
Fixed in bec546f1363892aa76f04e8619c5096eaf364a82, thank you!
