### ISSUE TITLE
Missing Assimp dependency for package/debian

### ISSUE THREAD

**Issue by leokolln** [mosra/magnum-plugins#39]
There is a missing dependency for `libassimp-dev` on the Debian package, making the `dpkg-buildpackage` fail at compilation (without clear message of why it failed) instead of during the dependency check, in case the library is not installed.

The dependency is missing at: https://github.com/mosra/magnum-plugins/blob/3ddca8fd230b252b19b1fb8a8927ba7c86836824/package/debian/control#L4

**Comment by leokolln** [comment]
Also recommend upgrade `libassimp3` to `libassimp3v5` as the former is not readily available in newer versions of Ubuntu.

**Comment by mosra** [comment]
Fixed in a66fd92acd98adb3adf1eed1ab9949db2abbdb30. Thank you!
