### ISSUE TITLE
Support Basis format files

### ISSUE THREAD

**Issue by jherico** [mosra/magnum-plugins#69]
[Basis universal](https://github.com/binomialLLC/basis_universal) is an open source GPU-oriented image format.  Images are stored in a compressed format (with compressed sizes comparable to PNG) but can be transcoded to a variety of compressed GPU formats (ASTC, ETC2, BC3) or to RGBA.  

This functionality allows developers to push a single asset to all platforms without worrying about which GPU compression formats are supported on the target.  

The basis format itself can store multiple images and multiple mips, so it _can_ be used comparably to DDS or KTX in functionality.  In fact a single basis file can store an entire texture catalog of varying image sizes, although it would probably be reasonable to implement logic that just loads the first image in a file

**Comment by mosra** [comment]
Hi, happy to see you here! 

In case you haven't seen: #62 and #65 ... and for vcpkg at least, we're relying on your fork :)

I'm just now in process of integrating the first of those PRs (pushing to the `next` branch for a CI run *soon* -- in the next hour or so), the second one is waiting for review comments to be addressed. Next step after those is KTX2 support so these can be used inside glTFs in a standardized way (as last time I checked `*.basis` couldn't be put there directly, only via a "private extension").

**Comment by jherico** [comment]
Oh, cool.  I didn't think to look in the PR tab since I assumed you'd have a tracking issue.  

I brought it up because I'm working on a set of OpenXR examples.  Since I want the code to be focused on the OpenXR API and not go too far into the weeds on how to render a scene I've been trying to sort out what to use as a rendering backend and Magnum seems like a good fit, but I also wanted to make sure I used basis and gltf for all assets, so good to hear work is in progress.  Thanks.

**Comment by mosra** [comment]
The [web player](https://magnum.graphics/showcase/player/) has a support now, if you want to check it out on random files: https://twitter.com/czmosra/status/1178089815021178884 (issue reports very welcome!)

Current magnum master (last push from ~1h ago) has additional compressed texture formats and some scaffolding needed by Basis added, and the `next` branch of this repo has the plugin working (and [CIs seem to be mostly happy](https://magnum.graphics/build-status/?mosra/corrade=next&mosra/magnum=next&mosra/magnum-plugins=next&mosra/magnum-extras=next&mosra/magnum-integration=next&mosra/magnum-bindings=next&mosra/magnum-examples=next&mosra/magnum-examples=ports-next&mosra/magnum-bootstrap=next&mosra/flextgl=next&mosra/magnum-singles=next&mosra/homebrew-magnum=next)). I still need to do a bunch of minor updates and commit the glTF support (which the web player has already), so ~ during tomorrow it could go to `master`. 

There's one unresolved issue about Y flip on importer that I'm planning to PR to Basis itself but as long as you pre-Y-flip during encoding, it won't bother you -- it's more an issue for general viewers/players that can't control how the file was produced.

**Comment by mosra** [comment]
#62 is merged now, [docs for it are up as well](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1BasisImporter.html). 

The converter part from #65 not yet, plus there's some work left to be done on the Basis side (see #70). Keeping this open until those two are resolved.

**Comment by mosra** [comment]
#65 is now merged, and since mosra/magnum@dac61f51cc0f1d5dd3a1a6706ae188579fbe63c9, the [magnum-imageconverter](https://doc.magnum.graphics/magnum/magnum-imageconverter.html) utility now supports passing options to it. So it can be used as a full replacement to the `basisu` tool, with support for many more input formats than just PNG.

What's left is #70 (and https://github.com/BinomialLLC/basis_universal/pull/79), but those are just minor interoperability issues, not blockers. So with that I'd consider Basis support being ready. I'm preparing a stable release with all this in the next week or so, subscribe to mosra/magnum#340 for updates.
