### ISSUE TITLE
Error loading greyscale + alpha files with PngImporter

### ISSUE THREAD

**Issue by williamjcm** [mosra/magnum-plugins#71]
When loading a greyscale + alpha PNG file using PngImporter, the importer crashes with the following error:

```text
Trade::PngImporter::image2D(): unsupported color type 4
```

Here's an image using that format:
![arms_sheet_mask](https://user-images.githubusercontent.com/13572456/67675104-9a36f800-f97e-11e9-8870-0631dcb71cea.png)

**Comment by mosra** [comment]
Hah, this kinda fell through the cracks, sorry about that.

Fixed in 8b60cd488e3dd0696957c410ec292445c3372e30, together with adding support for two-channel tRNS images (which were even non-gracefully asserting).
