### ISSUE TITLE
DrWavAudioImporterTest: cmake error when CORRADE_BUILD_STATIC=ON and BUILD_PLUGINS_STATIC=OFF

### ISSUE THREAD

**Issue by bowling-allie** [mosra/magnum-plugins#78]
https://github.com/mosra/magnum-plugins/blob/d78e390edbf0d1dea34588cf8d96d0ccf43ed1ce/src/MagnumPlugins/DrWavAudioImporter/Test/CMakeLists.txt#L102
DrWavImporterTest should be DrWavAudioImporterTest as far as I can tell.

**Comment by bowling-allie** [comment]
Just realized I already wrote the fix for this and i think its in the meshdata branch

**Comment by mosra** [comment]
Yep I commited this under your name, but then life stuff got in the way and so the push to master got delayed (e8e7ae2b08d4a19bdf179cf9041157671c4dcc1e) :)

Thanks for this! :+1:
