### ISSUE TITLE
FindMagnumPlugins.cmake interaction with Assimp

### ISSUE THREAD

**Issue by celentes** [mosra/magnum-plugins#87]
Documentation on using AssimpImporter recommends building assimp as a subproject:
```
add_subdirectory(assimp EXCLUDE_FROM_ALL)
add_library(Assimp::Assimp ALIAS assimp)
```
But I prefer to keep them globally installed, so I was trying to get that to work, and what I have noticed is that FindMagnumPlugins refers to it this way:
``` 
find_package(Assimp)
set_property(TARGET MagnumPlugins::${_component} APPEND PROPERTY INTERFACE_LINK_LIBRARIES Assimp::Assimp)
```
But pulling assimp from the master right now, I have noticed that it perfectly installs and provides assimp package with assimp::assimp as a target, and if I go ahead and change that to 
``` 
find_package(assimp)
set_property(TARGET MagnumPlugins::${_component} APPEND PROPERTY INTERFACE_LINK_LIBRARIES assimp::assimp)
```
then it works and finds it correctly.

**Comment by celentes** [comment]
Any reason I am missing to keep it inconsistent?

**Comment by mosra** [comment]
The (uppercase) `Assimp` package is searched for and exposed by magnum's own [FindAssimp.cmake](https://github.com/mosra/magnum-plugins/blob/master/modules/FindAssimp.cmake), so you'll need to copy that file into your `modules/` dir along with `FindMagnumPlugins`. The [docs mention both ways](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1AssimpImporter.html#Trade-AssimpImporter-usage), either a subproject setup or a system-wide installation, so you probably just missed the part that suggested to take the `FindAssimp` module also. 

That said, if you have an idea how to make the docs clearer, let me know, I'll fix them.

**Comment by mosra** [comment]
The reason why magnum has its own FindAssimp instead of `find_package(assimp CONFIG)`, btw., is because historically Assimp didn't provide a CMake imported target, it was missing various parts, or distributions didn't ship the cmake files from it. Plus `find_package(assimp CONFIG)` wouldn't work with Assimp as a CMake subproject, so the Find module kinda abstracts that away.

**Comment by mosra** [comment]
Ok, I think there's nothing left to do here. A related issue is mosra/magnum#436, which could avoid the need to explicitly copy the FindAssimp.cmake. Closing this in favor of that one.
