### ISSUE TITLE
AssimpImporter crashes on gltf/glb in wasm builds

### ISSUE THREAD

**Issue by celentes** [mosra/magnum-plugins#88]
Now, I am not entirely sure whether it's a magnum issue or an assimp issue - I suspect it is the latter.

After some series of shamanistic dances, I managed to get assimp importer compile and link correctly with emscripten-wasm toolchain, and generally speaking it works - tested it on OBJ and COLLADA files, works without a hitch - but crashes right off the bat on openFile() if I provide assimp-generated gltf or glb files.

Now, i've no idea how to debug that. I'll try to play around with building assimp/magnum in debug mode, but I haven't had any experience with wasm-side debugging yet.

**Comment by mosra** [comment]
Wow, assimp on emscripten. I admire your patience, never had the nerve to even try that myself :D

If you enable [ImporterFlag::Verbose](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Trade.html#a137d832c7ce6e6b654022321941d70f3ad4a9fa383ab700c5bdd6f31cf7df0faf), Assimp will print a ton of logs about opening the file, doing processing etc., so maybe that could point to something. How is the crash showing in the javascript console? Maybe it's just running out of memory or throwing some assert.

Does the gltf/glb file work when loaded natively? Or does it crash also?

Assimp is generally a pain, so in case of gltf/glb I'd suggest [TinyGltfImporter](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1TinyGltfImporter.html) instead -- it has much more complete support, knows various extensions and has >90% test coverage, unlike the code in assimp itself.

**Comment by celentes** [comment]
On native it works just fine. I should have mentioned, it was a 2019.10 release I was working with, no importer flags there yet - I'll bump it up to master and see how that goes.

Here's the error. Not much to go on.
```
EmscriptenApplication.js:35 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
printErr @ EmscriptenApplication.js:35
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
instantiateAsync @ magnum-viewer.js:1
createWasm @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1
EmscriptenApplication.js:35 falling back to ArrayBuffer instantiation
printErr @ EmscriptenApplication.js:35
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
instantiateAsync @ magnum-viewer.js:1
createWasm @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1
EmscriptenApplication.js:39 Renderer: WebKit WebGL by WebKit
EmscriptenApplication.js:39 OpenGL version: OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))
EmscriptenApplication.js:39 Using optional features:
EmscriptenApplication.js:39     GL_EXT_texture_filter_anisotropic
EmscriptenApplication.js:39 Opening file mellanplatta.gltf
EmscriptenApplication.js:35 exception thrown: 6114128
printErr @ EmscriptenApplication.js:35
callMain @ magnum-viewer.js:1
doRun @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1
setTimeout (async)
run @ magnum-viewer.js:1
runCaller @ magnum-viewer.js:1
removeRunDependency @ magnum-viewer.js:1
receiveInstance @ magnum-viewer.js:1
receiveInstantiatedSource @ magnum-viewer.js:1
Promise.then (async)
instantiateArrayBuffer @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
instantiateAsync @ magnum-viewer.js:1
createWasm @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1


magnum-viewer.js:1 Uncaught 6114128
quit_ @ magnum-viewer.js:1
callMain @ magnum-viewer.js:1
doRun @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1
setTimeout (async)
run @ magnum-viewer.js:1
runCaller @ magnum-viewer.js:1
removeRunDependency @ magnum-viewer.js:1
receiveInstance @ magnum-viewer.js:1
receiveInstantiatedSource @ magnum-viewer.js:1
Promise.then (async)
instantiateArrayBuffer @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
(anonymous) @ magnum-viewer.js:1
Promise.then (async)
instantiateAsync @ magnum-viewer.js:1
createWasm @ magnum-viewer.js:1
(anonymous) @ magnum-viewer.js:1
```

**Comment by celentes** [comment]
ok, with verbose flag it produces extra two lines:
```
Trade::AssimpImporter: Info,  T0: Load mellanplatta.gltf
Trade::AssimpImporter: Debug, T0: Assimp 5.0.2399955716 <unknown architecture> gcc shared singlethreaded
```
and then crashes :D

But yeah, tinygltfimporter works.

**Comment by celentes** [comment]
Looking at loading other file types, assimp reports finding an appropriate loader - here it doesn't get to that point. Maybe the devil is somewhere there.

**Comment by mosra** [comment]
Not sure what to do next -- is Emscripten even officially supported by Assimp? You could try reporting the bug there. You could build a non-release binary to (hopefully) see some backtrace and more info about the crash.

If you open the file natively (or with [`magnum-sceneconverter`](https://doc.magnum.graphics/magnum/magnum-sceneconverter.html)`--info -v`, if you have that built/installed), it should show much more log info than just these two lines alone. My conclusion is that this is definitely something fishy in their code and the importer plugin code is not to blame :)

Alternatively it could be due to unaligned reads/writes which used to be problematic with the wasm toolchain (but not anymore in recent versions), those would be *hard* to debug&fix.

**Comment by celentes** [comment]
Yeah, I'll take it to them if the need arises. I'll do a workaround with tinygltf, that seems to work.

Cheers

**Comment by mosra** [comment]
One useful thing when you have both assimp and tinygltf loaded is [setPreferredPlugins()](https://doc.magnum.graphics/corrade/classCorrade_1_1PluginManager_1_1AbstractManager.html#a93baed5663d354c0dd860676474de42c), with that you can control which plugin will be selected for which format.

To further remove the need for Assimp, i'm planning to either integrate tinyobjloader or improve magnum's builtin OBJ loader. COLLADA will however stay with Assimp, because the format is so overengineered that there's not really any nice, small and reliable library providing import for it.

**Comment by celentes** [comment]
Well, for what it's worth, I have compiled assimp with your wasm toolchain, having set a bunch of targets off and left just the import lib, built statically. 
The only caveat was that they build zlib and IrrXML and then link them _privately_, which ends up causing linker errors in fully static build - I solved this by telling cmake to link those .bc libs directly in the emscripten build of my project.

**Comment by mosra** [comment]
Thanks for sharing this info :+1: 

> The only caveat was that they build zlib and IrrXML and then link them privately

Latest CMake has a thing for this: https://cmake.org/cmake/help/latest/policy/CMP0099.html#policy:CMP0099 (`cmake_policy(SET CMP0099 NEW)` should make the privately linked properties transitive)
