### ISSUE TITLE
Having trouble statically linking to FreeTypeFont

### ISSUE THREAD

**Issue by LB--** [mosra/magnum-plugins#9]
I'm building Corrade, Mangum, and MagnumPlugins statically, and I need to use FreeTypeFont. However, `${MAGNUMPLUGINS_FreeTypeFont_LIBRARIES}` is empty for me (resulting in linker errors), even though the line `find_package(MagnumPlugins REQUIRED COMPONENTS FreeTypeFont)` succeeds. I have a full minimal test case [here](https://drive.google.com/file/d/0B6gYqBQuTG-9djIzRjZsMk14ZzQ/view?usp=sharing), and the output of my build log can be found [here](https://gist.github.com/LB--/0e8484afc71e86ea3165).

Excerpt from `Main.cpp`:
```cpp
static int load_corrade_plugins()
{
	CORRADE_PLUGIN_IMPORT(FreeTypeFont);
	return 0;
}
CORRADE_AUTOMATIC_INITIALIZER(load_corrade_plugins);
```
Excerpt from build log:
```txt
-- Found Corrade: C:/Users/LB/GitHub/magnum-plugins-bug/build/deps-install/lib/libCorradeUtility.a
-- Found OpenGL: opengl32
-- Found Magnum: C:/Users/LB/GitHub/magnum-plugins-bug/build/deps-install/lib/libMagnum.a  found components:  TextureTools Text
-- LIB_SUFFIX variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- LIB_SUFFIX autodetected as '', libraries will be installed into C:/Users/LB/GitHub/magnum-plugins-bug/build/deps-install/lib
-- Found Freetype: C:/Users/LB/Code/SFML-install/lib/libfreetype.a (found version "2.6.0")
-- Found MagnumPlugins: C:/Users/LB/GitHub/magnum-plugins-bug/build/deps-install/include/MagnumPlugins  found components:  FreeTypeFont
-- MAGNUMPLUGINS_FreeTypeFont_LIBRARIES=
-- Configuring done
```
The linker errors:
```txt
CMakeFiles\magnum-plugins-bug.dir/objects.a(Main.cpp.obj):Main.cpp:(.text+0x9): undefined reference to `pluginImporter_FreeTypeFont()'
CMakeFiles\magnum-plugins-bug.dir/objects.a(Main.cpp.obj):Main.cpp:(.text+0xe): undefined reference to `resourceInitializer_FreeTypeFont()'
```
I'm building with nuwen MinGW 5.2.0 on Windows 10 using CMake 3.3.1.

Note: everything works if I build shared libraries instead of static libraries, though obviously `${MAGNUMPLUGINS_FreeTypeFont_LIBRARIES}` is still empty. Build log for that can be found [here](https://gist.github.com/LB--/68b69a24834be74ccba5).

**Comment by mosra** [comment]
Hi, sorry for the delay, I was without sane internet connection. The problem is that you should be using all-uppercase variable names (thus `${MAGNUMPLUGINS_FREETYPEFONT_LIBRARIES}`. I assumed that it is a standard naming convention so I didn't mention it explicitly in the docs, sorry. I might do so now.

Secondly, `find_package(MagnumPlugins REQUIRED COMPONENTS FreeTypeFont)` -- according to CMake docs it should be either `REQUIRED` or `COMPONENTS` and not both. It probably doesn't result in any error, but might do so in some corner cases, so be warned :)

Hope this helps (and sorry again for the delays).

**Comment by LB--** [comment]
Waoh, I had no idea the case was the issue - I was just copypasting the names from the `FindMagnumPlugins.cmake` docs. As for find_package, I think this has changed in CMake 3, at least according to the [current documentation](https://cmake.org/cmake/help/latest/command/find_package.html). Either way, everything is working now - thanks!
