### ISSUE TITLE
Compile issues on osx

### ISSUE THREAD

**Issue by hsdk123** [mosra/magnum-plugins#90]
Errors:
`use of undeclared identifier CORRADE_INTERNAL_ASSERT_UNREACHABLE` in StbImageConverter.cpp (line 108)

I've pulled from Corrade master and am getting these issues.

**Comment by hsdk123** [comment]
Interesting thing is that even if I add `#include <Corrade/Utility/Assert.h>` manually, I still get the same compiler error. I'm assuming the macro isn't being properly declared.

**Comment by mosra** [comment]
Haha what. Are you really really really sure it's not pulling in some old version of Assert.h? :) This macro got added not so recently, so this is a probable cause.

**Comment by hsdk123** [comment]
>  Are you really really really sure it's not pulling in some old version of Assert.h? :)

That was my original guess as well, but xcode seems to be pointing to the file that has the declaration, so I'm not too sure what's happening...

I'll keep digging a bit more on my side as well

**Comment by hsdk123** [comment]
Seems this was a false error due to the other bug in the magnum repo, closing.
